defmodule Ash2385.Repo.Migrations.AddMyResourcesTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:my_resources, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add :balance, :decimal, precision: 15, scale: 5, null: false, default: "0"
    end
  end

  def down do
    drop(table(:my_resources))
  end
end
