defmodule Ash2385.Repo.Migrations.AddTimestamps do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:my_resources) do
      add(:inserted_at, :"timestamptz(6)",
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :"timestamptz(6)",
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end
  end

  def down do
    alter table(:my_resources) do
      remove(:updated_at)
      remove(:inserted_at)
    end
  end
end
